easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Package
        - App\Entity\PackageRequest
        - App\Entity\Release
        - App\Entity\User
