language: php
php:
    - '7.4'
os: linux
dist: xenial

addons:
    mariadb: '10.3'
    apt:
        update: true
    code_climate:
        repo_token:
            secure: ced3826aa9df61ac735f0e423a53b332223a874540b92ad09597c15a7df8e7b8

before_install:
    - sudo mysql -e 'CREATE DATABASE aur_test;'

install:
    - composer install
    - php bin/console doctrine:migrations:migrate --no-interaction --env=test
    - php bin/console doctrine:fixtures:load --no-interaction --env=test

before_script:
    - wget -O test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    - chmod +x ./test-reporter
    - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar
    - chmod +x php-coveralls.phar

script:
    - ./vendor/bin/phpcs
    - ./vendor/bin/phpstan analyse -c phpstan.neon
    - php bin/phpunit --testdox --coverage-clover ./tests/logs/clover.xml

after_script:
    - ./test-reporter after-build -t clover ./tests/logs/clover.xml
    - travis_retry php php-coveralls.phar -v
