language: php
php:
    - '7.4'
os: linux
dist: xenial

env:
    global:
        - CC_TEST_REPORTER_ID=ced3826aa9df61ac735f0e423a53b332223a874540b92ad09597c15a7df8e7b8

addons:
    mariadb: '10.3'
    apt:
        update: true

before_install:
    - sudo mysql -e 'CREATE DATABASE aur_test;'

install:
    - composer install
    - composer require php-coveralls/php-coveralls
    - php bin/console doctrine:migrations:migrate --no-interaction --env=test
    - php bin/console doctrine:fixtures:load --no-interaction --env=test

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

script:
    - ./vendor/bin/phpcs
    - ./vendor/bin/phpstan analyse -c phpstan.neon
    - php bin/phpunit --testdox --coverage-clover ./tests/logs/clover.xml

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - php vendor/bin/coveralls -v
