language: php
php:
    - '7.4'
    - nightly
os: linux
dist: xenial

addons:
    mariadb: '10.3'
    apt:
        update: true

before_install:
    - mysql -e 'CREATE DATABASE aur_test;'
    - mysql -u root -e "GRANT ALL PRIVILEGES ON mydb.* TO 'travis'@'%';";

install:
    - composer install
    - php bin/console doctrine:migrations:migrate --no-interaction --env=test
    - php bin/console doctrine:fixtures:load --no-interaction --env=test

script:
    - ./vendor/bin/phpcs
    - ./vendor/bin/phpstan analyse -c phpstan.neon
    - php bin/phpunit --testdox
