language: php
php:
    - '7.4'
    - nightly

services:
    - mariadb
addons:
    mariadb: '10.3'
    apt:
        update: true

before_install:
    - mysql -e 'CREATE DATABASE aur_test;'

install:
    - composer install
    - php bin/console doctrine:migrations:migrate --force --env=test
    - php bin/console doctrine:fixtures:load --no-interaction --env=test

script:
    - ./vendor/bin/phpcs
    - ./vendor/bin/phpstan analyse -c phpstan.neon
    - php bin/phpunit --testdox
