language: php
php:
    - '7.4'
os: linux
dist: xenial

addons:
    mariadb: '10.4'
    apt:
        update: true

before_install:
    - sudo mysql -e 'CREATE DATABASE aur_test;'

install:
    - composer install
    - php bin/console doctrine:migrations:migrate --no-interaction --env=test
    - php bin/console doctrine:fixtures:load --no-interaction --env=test

script:
    - ./vendor/bin/phpcs
    - ./vendor/bin/phpstan analyse -c phpstan.neon
    - php bin/phpunit --testdox
