name: phpcs
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: PHP Code Style (phpcs)
              uses: chindit/actions-phpcs@#3_add_cli_args
              with:
                  # Folder to check code style
                  dir: src/
                  cli: '--version'
