name: phpcs
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: PHP Code Style (phpcs)
        uses: chindit/actions-phpcs@debug/missing_directory
        with:
          # Folder to check code style
          dir: src
