name: phpcs
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: PHPStan
        uses: chindit/actions-phpstan@master
        with:
          # Folder to check code style
          dir: src/
