name: phpcs
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHPStan
        uses: chindit/actions-phpstan@master
        with:
          arguments: analyse src/ --level=7

      - name: PHPCS
        uses: chindit/actions-phpcs@master
        with:
          dir: src/

      - name: PHPUnit
        uses: chindit/actions-phpunit-symfony@master
