name: phpcs
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
services:
  mysql:
    image: mysql:5.7
    env:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: aur_test
    ports:
      - 3306
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Setup fixtures
        run: php bin/console doctrine:fixtures:load --no-interaction

      - name: PHPStan
        uses: chindit/actions-phpstan@master

      - name: PHPCS
        uses: chindit/actions-phpcs@master

      - name: PHPUnit
        uses: chindit/actions-phpunit-symfony@master
