name: phpcs
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: PHPStan
        uses: chindit/actions-phpstan@master

      - name: PHPCS
        uses: chindit/actions-phpcs@master

      - name: PHPUnit
        uses: chindit/actions-phpunit-symfony@master
